services:
  - type: web
    name: cosmic-space-protocol
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://cosmic-space-protocol.onrender.com
    autoDeploy: true 